# Generated by Django 2.1.4 on 2019-07-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appe', '0002_vendor_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_details',
            name='EMAIL',
            field=models.EmailField(max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendor_details',
            name='USERNAME',
            field=models.CharField(max_length=150),
        ),
    ]
