# Generated by Django 2.1.4 on 2019-07-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appe', '0003_auto_20190718_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_details',
            name='EMAIL',
            field=models.EmailField(max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer_details',
            name='USERNAME',
            field=models.CharField(max_length=150),
        ),
    ]
