# Generated by Django 2.1.4 on 2019-07-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appe', '0005_customer_details_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_newproduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TYPE', models.CharField(max_length=50)),
                ('CATEGORIES', models.CharField(max_length=50)),
                ('CATEGORIETYPE', models.CharField(max_length=50)),
                ('SIZE', models.CharField(max_length=20)),
                ('QUANTITY', models.CharField(max_length=50)),
                ('NAME', models.CharField(max_length=100)),
                ('IMAGE', models.ImageField(default=False, upload_to='my_images')),
                ('PRICE', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DESCRIPTION', models.CharField(max_length=500)),
            ],
        ),
    ]
